# Generated by Django 5.2.17 on 2026-08-27 03:45

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('fleet_core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Run',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('blueprint_ir', models.JSONField()),
                ('trigger_kind', models.CharField(choices=[('chat', 'Chat'), ('manual', 'Manual'), ('schedule', 'Schedule'), ('webhook', 'Webhook'), ('agent', 'Agent')], max_length=16)),
                ('input_text', models.TextField(blank=True)),
                ('state', models.CharField(choices=[('queued', 'Queued'), ('running', 'Running'), ('succeeded', 'Succeeded'), ('failed', 'Failed'), ('killed', 'Killed'), ('budget_stopped', 'Budget Stopped')], default='queued', max_length=16)),
                ('error', models.JSONField(blank=True, null=True)),
                ('cost_microusd_total', models.BigIntegerField(default=0)),
                ('tokens_in_total', models.BigIntegerField(default=0)),
                ('tokens_out_total', models.BigIntegerField(default=0)),
                ('callback_token_hash', models.CharField(max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='fleet_core.workspace')),
            ],
        ),
        migrations.CreateModel(
            name='LedgerEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('actor_kind', models.CharField(max_length=16)),
                ('actor_id', models.CharField(blank=True, max_length=64)),
                ('action', models.CharField(max_length=64)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='fleet_core.workspace')),
                ('run', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='fleet_runs.run')),
            ],
        ),
        migrations.CreateModel(
            name='RunStep',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('step_index', models.IntegerField()),
                ('kind', models.CharField(choices=[('system', 'System'), ('model_call', 'Model Call'), ('tool_call', 'Tool Call'), ('memory_retrieval', 'Memory Retrieval'), ('policy_check', 'Policy Check'), ('budget_check', 'Budget Check')], max_length=24)),
                ('provider', models.CharField(blank=True, max_length=40)),
                ('request_payload', models.JSONField(blank=True, null=True)),
                ('response_payload', models.JSONField(blank=True, null=True)),
                ('rng_seed', models.BigIntegerField(blank=True, null=True)),
                ('clock_reads', models.JSONField(blank=True, default=list)),
                ('tokens_in', models.IntegerField(default=0)),
                ('tokens_out', models.IntegerField(default=0)),
                ('cost_microusd', models.BigIntegerField(default=0)),
                ('price_table_version', models.CharField(blank=True, max_length=40)),
                ('duration_ms', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='steps', to='fleet_runs.run')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='fleet_core.workspace')),
            ],
            options={
                'ordering': ['step_index'],
            },
        ),
        migrations.AddIndex(
            model_name='run',
            index=models.Index(fields=['workspace', '-created_at'], name='fleet_runs__workspa_efffea_idx'),
        ),
        migrations.AddIndex(
            model_name='run',
            index=models.Index(fields=['workspace', 'state'], name='fleet_runs__workspa_42d4d6_idx'),
        ),
        migrations.AddIndex(
            model_name='ledgerentry',
            index=models.Index(fields=['workspace', '-created_at'], name='fleet_runs__workspa_31dc8e_idx'),
        ),
        migrations.AddIndex(
            model_name='ledgerentry',
            index=models.Index(fields=['workspace', 'run'], name='fleet_runs__workspa_6e8cde_idx'),
        ),
        migrations.AddIndex(
            model_name='runstep',
            index=models.Index(fields=['workspace', 'run'], name='fleet_runs__workspa_70013b_idx'),
        ),
        migrations.AddConstraint(
            model_name='runstep',
            constraint=models.UniqueConstraint(fields=('run', 'step_index'), name='uniq_run_step_index'),
        ),
    ]
